name: Manual-Workflow

# Controls when the workflow will run
on:
  workflow_dispatch: # Allows manual triggering of the workflow

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks out the repository under $GITHUB_WORKSPACE, so your job can access it  
      - name: Checkout repository
        uses: actions/checkout@v5

      # Runs a single command using the runners shell  
      - name: Run a one-line script
        run: echo "Hello, world!"
      - name: Ru a multi-line script
        run: |
          echo "This is a multi-line script."
          echo "It can run multiple commands."
          echo "Each command is on a new line."