name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow when code is pushed to the main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Run a one-line script
        run: echo "Hello, world!"
      - name: Ru a multi-line script
        run: |
          echo "This is a multi-line script."
          echo "It can run multiple commands."
          echo "Each command is on a new line."

